# Generated by Django 5.2 on 2025-06-10 04:52

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import xaridorlar.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Xaridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familiya', models.CharField(max_length=100, verbose_name='Ism va Familiya')),
                ('telefon_raqam', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Masalan: +998901234567', max_length=128, null=True, region=None, verbose_name='Telefon Raqam')),
                ('hozirgi_balans', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hozirgi Balans')),
                ('sana', models.DateField(verbose_name='Sana')),
                ('izoh', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xaridorlar', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xaridor',
                'verbose_name_plural': 'Xaridorlar',
            },
        ),
        migrations.CreateModel(
            name='XaridorHujjat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hujjat', models.FileField(upload_to=xaridorlar.models.generate_unique_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx']), xaridorlar.models.validate_file_size], verbose_name='Hujjat fayli')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Asl fayl nomi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('xaridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hujjatlar', to='xaridorlar.xaridor', verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': 'Xaridor hujjati',
                'verbose_name_plural': 'Xaridor hujjatlari',
            },
        ),
        migrations.AddIndex(
            model_name='xaridor',
            index=models.Index(fields=['user'], name='xaridorlar__user_id_b6ef3d_idx'),
        ),
        migrations.AddIndex(
            model_name='xaridor',
            index=models.Index(fields=['ism_familiya'], name='xaridorlar__ism_fam_a95933_idx'),
        ),
        migrations.AddIndex(
            model_name='xaridorhujjat',
            index=models.Index(fields=['xaridor'], name='xaridorlar__xaridor_33cec2_idx'),
        ),
    ]
