# Generated by Django 5.2 on 2025-05-28 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xaridorlar', '0002_alter_xaridor_telefon_raqam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xaridor',
            name='telefon_raqam',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Raqam'),
        ),
        migrations.AlterField(
            model_name='xaridorhujjat',
            name='hujjat',
            field=models.FileField(upload_to='xaridor_hujjatlar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'])], verbose_name='Hujjat fayli'),
        ),
    ]
