# Generated by Django 5.2 on 2025-05-29 22:01

import django.core.validators
import xaridorlar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xaridorlar', '0003_alter_xaridor_telefon_raqam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xaridorhujjat',
            name='hujjat_turi',
            field=models.CharField(choices=[('passport', 'Pasport'), ('shartnoma', 'Shartnoma'), ('boshqa', 'Boshqa')], default='boshqa', max_length=50, verbose_name='Hujjat turi'),
        ),
        migrations.AlterField(
            model_name='xaridorhujjat',
            name='hujjat',
            field=models.FileField(upload_to=xaridorlar.models.generate_unique_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'])], verbose_name='Hujjat fayli'),
        ),
    ]
