# Generated by Django 5.2 on 2025-05-29 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xaridorlar', '0004_xaridorhujjat_hujjat_turi_alter_xaridorhujjat_hujjat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xaridorhujjat',
            name='hujjat_turi',
        ),
        migrations.AlterField(
            model_name='xaridorhujjat',
            name='hujjat',
            field=models.FileField(upload_to='xaridor_hujjatlar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'])], verbose_name='Hujjat fayli'),
        ),
    ]
