# Generated by Django 5.2 on 2025-06-03 06:05

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import xaridorlar.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xaridorlar', '0005_remove_xaridorhujjat_hujjat_turi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xaridorhujjat',
            name='original_file_name',
        ),
        migrations.AlterField(
            model_name='xaridor',
            name='telefon_raqam',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Masalan: +998901234567', max_length=128, null=True, region=None, verbose_name='Telefon Raqam'),
        ),
        migrations.AlterField(
            model_name='xaridorhujjat',
            name='hujjat',
            field=models.FileField(upload_to=xaridorlar.models.generate_unique_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx']), xaridorlar.models.validate_file_size], verbose_name='Hujjat fayli'),
        ),
        migrations.AlterField(
            model_name='xaridorhujjat',
            name='xaridor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hujjatlar', to='xaridorlar.xaridor', verbose_name='Xaridor'),
        ),
        migrations.AddIndex(
            model_name='xaridor',
            index=models.Index(fields=['user'], name='xaridorlar__user_id_b6ef3d_idx'),
        ),
        migrations.AddIndex(
            model_name='xaridor',
            index=models.Index(fields=['ism_familiya'], name='xaridorlar__ism_fam_a95933_idx'),
        ),
        migrations.AddIndex(
            model_name='xaridorhujjat',
            index=models.Index(fields=['xaridor'], name='xaridorlar__xaridor_33cec2_idx'),
        ),
    ]
