# Generated by Django 5.2 on 2025-06-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xaridorlar', '0006_remove_xaridorhujjat_original_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xaridorhujjat',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Asl fayl nomi'),
        ),
    ]
