# Generated by Django 5.2 on 2025-06-03 07:44

import django.core.validators
import xaridorlar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xaridorlar', '0007_xaridorhujjat_original_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xaridor',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='xaridorhujjat',
            name='hujjat',
            field=models.FileField(upload_to=xaridorlar.models.generate_unique_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'])], verbose_name='Hujjat fayli'),
        ),
    ]
