# Generated by Django 5.2 on 2025-06-03 07:48

import django.core.validators
import django.utils.timezone
import xaridorlar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xaridorlar', '0008_remove_xaridor_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='Xaridor',
            name='created_date',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='Yaratilgan sana'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='XaridorHujjat',
            name='hujjat',
            field=models.FileField(
                upload_to=xaridorlar.models.generate_unique_filename,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx']
                    ),
                    xaridorlar.models.validate_file_size
                ],
                verbose_name='Hujjat fayli'
            ),
        ),
    ]