# Generated by Django 5.2 on 2025-06-10 04:52

import chiqim.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '0001_initial'),
        ('xaridorlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chiqim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Umumiy narx')),
                ('boshlangich_summa', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Boshlang'ich to'lov (rejalashtirilgan)")),
                ('qoldiq_summa', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Qoldiq summa')),
                ('hujjatlar', models.FileField(blank=True, null=True, upload_to=chiqim.models.generate_unique_chiqim_filename, verbose_name='Hujjatlar')),
                ('bo_lib_tolov_muddat', models.PositiveIntegerField(default=0, verbose_name="Bo'lib to'lash muddati (oy)")),
                ('oyiga_tolov', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Oyiga to'lov")),
                ('tolov_sana', models.DateField(verbose_name="Birinchi to'lov sanasi")),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('sana', models.DateField(auto_now_add=True, verbose_name='Sotish sanasi')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiqim', to='trucks.truck', verbose_name='Mashina')),
                ('xaridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiqim', to='xaridorlar.xaridor', verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': 'Chiqim',
                'verbose_name_plural': 'Chiqimlar',
            },
        ),
        migrations.CreateModel(
            name='BoshlangichTolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolov_turi', models.CharField(choices=[('zelle', 'Zelle'), ('wire_transfer', 'Wire Transfer'), ('cash', 'Naqd'), ('button', 'Button')], max_length=20, verbose_name='Tolov turi')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tolov summasi')),
                ('firma_nomi', models.CharField(blank=True, max_length=200, verbose_name='Firma nomi')),
                ('bank', models.CharField(blank=True, max_length=100, verbose_name='Tolov qilingan bank')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('sana', models.DateField(verbose_name="To'lov sanasi")),
                ('is_partial', models.BooleanField(default=False, verbose_name="Qisman to'lov")),
                ('xaridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xaridorlar.xaridor', verbose_name='Xaridor')),
                ('chiqim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boshlangich_tolovlar', to='chiqim.chiqim', verbose_name='Chiqim')),
            ],
            options={
                'verbose_name': "Boshlang'ich To'lov",
                'verbose_name_plural': "Boshlang'ich To'lovlar",
            },
        ),
        migrations.CreateModel(
            name='Bildirishnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolov_sana', models.DateField(verbose_name="To'lov sanasi")),
                ('eslatma', models.BooleanField(default=False, verbose_name='Eslatildi')),
                ('eslatish_kunlari', models.PositiveIntegerField(default=30, verbose_name='Eslatishdan oldin kunlar')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('overdue', 'Qarz'), ('urgent', 'Tez kunda'), ('warning', 'Ogohlantirish')], default='pending', max_length=10, verbose_name='Holati')),
                ('sana', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arxivlangan')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='SMS Yuborildi')),
                ('chiqim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirishnomalar', to='chiqim.chiqim', verbose_name='Chiqim')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['tolov_sana'],
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='SMS Matni')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan Vaqt')),
                ('status', models.CharField(choices=[('sent', 'Yuborildi'), ('failed', 'Xato')], default='sent', max_length=10, verbose_name='Holati')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xato Xabari')),
                ('bildirishnoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='chiqim.bildirishnoma', verbose_name='Bildirishnoma')),
                ('xaridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='xaridorlar.xaridor', verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': 'SMS Tarixi',
                'verbose_name_plural': 'SMS Tarixlari',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='TolovTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolov_turi', models.CharField(choices=[('zelle', 'Zelle'), ('wire_transfer', 'Wire Transfer'), ('cash', 'Naqd'), ('button', 'Button')], max_length=20, verbose_name='Tolov turi')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tolov summasi')),
                ('firma_nomi', models.CharField(blank=True, max_length=200, verbose_name='Firma nomi')),
                ('bank', models.CharField(blank=True, max_length=100, verbose_name='Tolov qilingan bank')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('sana', models.DateField(verbose_name="To'lov sanasi")),
                ('is_partial', models.BooleanField(default=False, verbose_name="Qisman to'lov")),
                ('chiqim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar', to='chiqim.chiqim', verbose_name='Chiqim')),
                ('xaridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xaridorlar.xaridor', verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
            },
        ),
        migrations.AddIndex(
            model_name='chiqim',
            index=models.Index(fields=['sana'], name='chiqim_chiq_sana_a63a29_idx'),
        ),
        migrations.AddIndex(
            model_name='chiqim',
            index=models.Index(fields=['tolov_sana'], name='chiqim_chiq_tolov_s_977c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='boshlangichtolov',
            index=models.Index(fields=['sana'], name='chiqim_bosh_sana_263eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='bildirishnoma',
            index=models.Index(fields=['tolov_sana'], name='chiqim_bild_tolov_s_1954cd_idx'),
        ),
        migrations.AddIndex(
            model_name='bildirishnoma',
            index=models.Index(fields=['status'], name='chiqim_bild_status_b30956_idx'),
        ),
        migrations.AddIndex(
            model_name='tolovturi',
            index=models.Index(fields=['sana'], name='chiqim_tolo_sana_994e5b_idx'),
        ),
    ]
