# Generated by Django 5.2 on 2025-05-28 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tolovturi',
            options={'verbose_name': 'To‘lov', 'verbose_name_plural': 'To‘lovlar'},
        ),
        migrations.AlterField(
            model_name='bildirishnoma',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', 'To‘langan'), ('overdue', 'Qarz'), ('urgent', 'Tez kunda'), ('warning', 'Ogohlantirish')], default='pending', max_length=10, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='bildirishnoma',
            name='tolov_sana',
            field=models.DateField(verbose_name='To‘lov sanasi'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='bo_lib_tolov_muddat',
            field=models.PositiveIntegerField(default=0, verbose_name='Bo‘lib to‘lash muddati (oy)'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='oyiga_tolov',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Oyiga to‘lov'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='tolangan_summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Boshlang‘ich to‘lov'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='tolov_sana',
            field=models.DateField(verbose_name='Birinchi to‘lov sanasi'),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='is_partial',
            field=models.BooleanField(default=False, verbose_name='Qisman to‘lov'),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='sana',
            field=models.DateField(auto_now_add=True, verbose_name='To‘lov sanasi'),
        ),
        migrations.CreateModel(
            name='SmsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_sms_limit', models.PositiveIntegerField(default=2, verbose_name='Kunlik SMS limiti')),
                ('allow_email_fallback', models.BooleanField(default=True, verbose_name='Email muqobil sifatida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'SMS Sozlamalari',
                'verbose_name_plural': 'SMS Sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Xaridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familiya', models.CharField(max_length=200, verbose_name='Ism Familiya')),
                ('telefon_raqam', models.CharField(max_length=20, verbose_name='Telefon Raqami')),
                ('hozirgi_balans', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Hozirgi Balans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xaridor',
                'verbose_name_plural': 'Xaridorlar',
            },
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='xaridor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiqim', to='chiqim.xaridor', verbose_name='Xaridor'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='xaridor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='chiqim.xaridor', verbose_name='Xaridor'),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='xaridor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chiqim.xaridor', verbose_name='Xaridor'),
        ),
    ]
