# Generated by Django 5.2 on 2025-05-28 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0002_alter_tolovturi_options_alter_bildirishnoma_status_and_more'),
        ('xaridorlar', '0003_alter_xaridor_telefon_raqam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xaridor',
            name='user',
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='xaridor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiqim', to='xaridorlar.xaridor', verbose_name='Xaridor'),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='xaridor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xaridorlar.xaridor', verbose_name='Xaridor'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='xaridor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='xaridorlar.xaridor', verbose_name='Xaridor'),
        ),
        migrations.AlterModelOptions(
            name='tolovturi',
            options={'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AlterField(
            model_name='bildirishnoma',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('overdue', 'Qarz'), ('urgent', 'Tez kunda'), ('warning', 'Ogohlantirish')], default='pending', max_length=10, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='bildirishnoma',
            name='tolov_sana',
            field=models.DateField(verbose_name="To'lov sanasi"),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='bo_lib_tolov_muddat',
            field=models.PositiveIntegerField(default=0, verbose_name="Bo'lib to'lash muddati (oy)"),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='oyiga_tolov',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Oyiga to'lov"),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='tolangan_summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Boshlang'ich to'lov"),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='tolov_sana',
            field=models.DateField(verbose_name="Birinchi to'lov sanasi"),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='is_partial',
            field=models.BooleanField(default=False, verbose_name="Qisman to'lov"),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='sana',
            field=models.DateField(auto_now_add=True, verbose_name="To'lov sanasi"),
        ),
        migrations.DeleteModel(
            name='SmsConfig',
        ),
        migrations.DeleteModel(
            name='Xaridor',
        ),
    ]
