# Generated by Django 5.2 on 2025-05-28 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0003_remove_xaridor_user_alter_chiqim_xaridor_and_more'),
        ('xaridorlar', '0003_alter_xaridor_telefon_raqam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_sms_limit', models.PositiveIntegerField(default=2, help_text='Bir kunda xaridorga yuboriladigan SMS lar soni', verbose_name='Kunlik SMS limiti')),
                ('allow_email_fallback', models.BooleanField(default=True, help_text="SMS yuborish muvaffaqiyatsiz bo'lsa, email orqali eslatma yuborish", verbose_name='Email zaxirasi ruxsat etilsinmi')),
                ('minimum_balance_threshold', models.DecimalField(decimal_places=2, default=5.0, help_text="Twilio balans bu qiymatdan past bo'lsa, ogohlantirish yuboriladi", max_digits=10, verbose_name='Minimal balans ogohlantirish chegarasi')),
                ('is_active', models.BooleanField(default=True, help_text="SMS yuborish tizimi faol yoki yo'qligini belgilaydi", verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('xaridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_configs', to='xaridorlar.xaridor', verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': 'SMS Sozlamasi',
                'verbose_name_plural': 'SMS Sozlamalari',
                'indexes': [models.Index(fields=['xaridor'], name='chiqim_smsc_xaridor_2feb3b_idx'), models.Index(fields=['is_active'], name='chiqim_smsc_is_acti_65852e_idx')],
                'constraints': [models.UniqueConstraint(fields=('xaridor',), name='unique_sms_config_per_xaridor')],
            },
        ),
    ]
