# Generated by Django 5.2 on 2025-05-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0004_smsconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsconfig',
            name='allow_email_fallback',
        ),
        migrations.AlterField(
            model_name='smsconfig',
            name='minimum_balance_threshold',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text="Twilio balans bu qiymatdan past bo'lsa, ogohlantirish yuzaga keladi", max_digits=10, verbose_name='Minimal balans ogohlantirish chegarasi'),
        ),
    ]
