# Generated by Django 5.2 on 2025-05-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0005_remove_smsconfig_allow_email_fallback_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmsConfig',
        ),
    ]
