# Generated by Django 5.2 on 2025-06-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0006_delete_smsconfig'),
        ('xaridorlar', '0005_remove_xaridorhujjat_hujjat_turi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chiqim',
            old_name='tolangan_summa',
            new_name='boshlangich_tolov',
        ),
        migrations.RemoveField(
            model_name='chiqim',
            name='qoldiq_summa',
        ),
        migrations.AddField(
            model_name='chiqim',
            name='boshlangich_qoldiq_summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Boshlang'ich qoldiq summa"),
        ),
        migrations.AddField(
            model_name='chiqim',
            name='boshlangich_tolangan_summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Boshlang'ich to'langan summa"),
        ),
        migrations.AddField(
            model_name='chiqim',
            name='oylik_qoldiq_summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Oylik qoldiq summa'),
        ),
        migrations.AddField(
            model_name='tolovturi',
            name='is_initial_payment',
            field=models.BooleanField(default=False, verbose_name="Boshlang'ich to'lovmi"),
        ),
        migrations.AddIndex(
            model_name='tolovturi',
            index=models.Index(fields=['is_initial_payment'], name='chiqim_tolo_is_init_f3f707_idx'),
        ),
    ]
