# Generated by Django 5.2 on 2025-06-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0007_rename_tolangan_summa_chiqim_boshlangich_tolov_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiqim',
            name='boshlangich_qoldiq_summa',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name="Boshlang'ich qoldiq summa"),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='oylik_qoldiq_summa',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Oylik qoldiq summa'),
        ),
    ]
