# Generated by Django 5.2 on 2025-06-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0008_alter_chiqim_boshlangich_qoldiq_summa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiqim',
            name='oyiga_tolov',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Oyiga to'lov"),
        ),
    ]
