# Generated by Django 5.2 on 2025-06-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0009_alter_chiqim_oyiga_tolov'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tolovturi',
            name='chiqim_tolo_is_init_f3f707_idx',
        ),
        migrations.RenameField(
            model_name='chiqim',
            old_name='boshlangich_tolov',
            new_name='tolangan_summa',
        ),
        migrations.RemoveField(
            model_name='chiqim',
            name='boshlangich_qoldiq_summa',
        ),
        migrations.RemoveField(
            model_name='chiqim',
            name='boshlangich_tolangan_summa',
        ),
        migrations.RemoveField(
            model_name='chiqim',
            name='oylik_qoldiq_summa',
        ),
        migrations.RemoveField(
            model_name='tolovturi',
            name='is_initial_payment',
        ),
        migrations.AddField(
            model_name='chiqim',
            name='qoldiq_summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Qoldiq summa'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='oyiga_tolov',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Oyiga to'lov"),
        ),
    ]
