# Generated by Django 5.2 on 2025-06-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0010_remove_tolovturi_chiqim_tolo_is_init_f3f707_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiqim',
            name='tolangan_summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Boshlang'ich to'lov (kerakli)"),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='tolov_turi',
            field=models.CharField(choices=[('initial_payment', "Boshlang'ich to'lov"), ('monthly_payment', "Oylik to'lov"), ('zelle', 'Zelle'), ('wire_transfer', 'Wire Transfer'), ('cash', 'Naqd'), ('button', 'Button')], max_length=20, verbose_name='Tolov turi'),
        ),
    ]
