# Generated by Django 5.2 on 2025-06-02 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0011_alter_chiqim_tolangan_summa_and_more'),
        ('xaridorlar', '0005_remove_xaridorhujjat_hujjat_turi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiqim',
            name='boshlangich_qarzdorlik',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Boshlang'ich qarzdorlik"),
        ),
        migrations.AddField(
            model_name='chiqim',
            name='boshlangich_tolov',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Boshlang'ich to'lov"),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='tolangan_summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Boshlang'ich to'langan summa"),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='tolov_turi',
            field=models.CharField(choices=[('zelle', 'Zelle'), ('wire_transfer', 'Wire Transfer'), ('cash', 'Naqd'), ('button', 'Button')], max_length=20, verbose_name='Tolov turi'),
        ),
        migrations.CreateModel(
            name='BoshlangichTolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolov_turi', models.CharField(choices=[('zelle', 'Zelle'), ('wire_transfer', 'Wire Transfer'), ('cash', 'Naqd'), ('button', 'Button')], max_length=20, verbose_name='Tolov turi')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tolov summasi')),
                ('firma_nomi', models.CharField(blank=True, max_length=200, verbose_name='Firma nomi')),
                ('bank', models.CharField(blank=True, max_length=100, verbose_name='Tolov qilingan bank')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('sana', models.DateField(auto_now_add=True, verbose_name="To'lov sanasi")),
                ('chiqim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boshlangich_tolovlar', to='chiqim.chiqim', verbose_name='Chiqim')),
                ('xaridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xaridorlar.xaridor', verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': "Boshlang'ich To'lov",
                'verbose_name_plural': "Boshlang'ich To'lovlar",
                'indexes': [models.Index(fields=['sana'], name='chiqim_bosh_sana_263eb6_idx')],
            },
        ),
    ]
