# Generated by Django 5.2 on 2025-06-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0012_chiqim_boshlangich_qarzdorlik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boshlangichtolov',
            name='sana',
            field=models.DateField(verbose_name="To'lov sanasi"),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='sana',
            field=models.DateField(verbose_name="To'lov sanasi"),
        ),
    ]
