# Generated by Django 5.2 on 2025-06-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0013_alter_boshlangichtolov_sana_alter_tolovturi_sana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chiqim',
            name='boshlangich_qarzdorlik',
        ),
        migrations.RemoveField(
            model_name='chiqim',
            name='boshlangich_tolov',
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='tolangan_summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Boshlang'ich to'lov"),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='sana',
            field=models.DateField(auto_now_add=True, verbose_name="To'lov sanasi"),
        ),
        migrations.DeleteModel(
            name='BoshlangichTolov',
        ),
    ]
