# Generated by Django 5.2 on 2025-06-03 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0014_remove_chiqim_boshlangich_qarzdorlik_and_more'),
        ('trucks', '0015_alter_truck_options_alter_truckhujjat_options_and_more'),
        ('xaridorlar', '0005_remove_xaridorhujjat_hujjat_turi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoshlangichTolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolov_turi', models.CharField(choices=[('zelle', 'Zelle'), ('wire_transfer', 'Wire Transfer'), ('cash', 'Naqd'), ('button', 'Button')], max_length=20, verbose_name="To'lov turi")),
                ('summa', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="To'lov summasi")),
                ('firma_nomi', models.CharField(blank=True, max_length=200, verbose_name='Firma nomi')),
                ('bank', models.CharField(blank=True, max_length=100, verbose_name="To'lov qilingan bank")),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('sana', models.DateField(verbose_name="To'lov sanasi")),
            ],
            options={
                'verbose_name': "Boshlang'ich To'lov",
                'verbose_name_plural': "Boshlang'ich To'lovlar",
            },
        ),
        migrations.AlterModelOptions(
            name='smslog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'SMS tarixi', 'verbose_name_plural': 'SMS tarixlari'},
        ),
        migrations.AddField(
            model_name='chiqim',
            name='boshlangich_qarzdorlik',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Boshlang'ich qarzdorlik"),
        ),
        migrations.AddField(
            model_name='chiqim',
            name='boshlangich_tolov',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Boshlang'ich to'lov"),
        ),
        migrations.AlterField(
            model_name='bildirishnoma',
            name='sms_sent',
            field=models.BooleanField(default=False, verbose_name='SMS yuborildi'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='tolangan_summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Boshlang'ich to'langan summa"),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Xato xabari'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='message',
            field=models.TextField(verbose_name='SMS matni'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='bank',
            field=models.CharField(blank=True, max_length=100, verbose_name="To'lov qilingan bank"),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='sana',
            field=models.DateField(verbose_name="To'lov sanasi"),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='summa',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name="To'lov summasi"),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='tolov_turi',
            field=models.CharField(choices=[('zelle', 'Zelle'), ('wire_transfer', 'Wire Transfer'), ('cash', 'Naqd'), ('button', 'Button')], max_length=20, verbose_name="To'lov turi"),
        ),
        migrations.AddIndex(
            model_name='bildirishnoma',
            index=models.Index(fields=['chiqim', 'status'], name='chiqim_bild_chiqim__1dc9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='chiqim',
            index=models.Index(fields=['xaridor', 'truck'], name='chiqim_chiq_xaridor_4174d9_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['sent_at'], name='chiqim_smsl_sent_at_214f53_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['bildirishnoma', 'xaridor'], name='chiqim_smsl_bildiri_5727f1_idx'),
        ),
        migrations.AddIndex(
            model_name='tolovturi',
            index=models.Index(fields=['chiqim', 'xaridor'], name='chiqim_tolo_chiqim__1e18de_idx'),
        ),
        migrations.AddField(
            model_name='boshlangichtolov',
            name='chiqim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boshlangich_tolovlar', to='chiqim.chiqim', verbose_name='Chiqim'),
        ),
        migrations.AddField(
            model_name='boshlangichtolov',
            name='xaridor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xaridorlar.xaridor', verbose_name='Xaridor'),
        ),
        migrations.AddIndex(
            model_name='boshlangichtolov',
            index=models.Index(fields=['sana'], name='chiqim_bosh_sana_263eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='boshlangichtolov',
            index=models.Index(fields=['chiqim', 'xaridor'], name='chiqim_bosh_chiqim__b42af6_idx'),
        ),
    ]
