# Generated by Django 5.2 on 2025-06-03 05:57

import chiqim.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0016_remove_boshlangichtolov_chiqim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiqim',
            name='hujjatlar',
            field=models.FileField(blank=True, null=True, upload_to=chiqim.models.generate_unique_chiqim_filename, verbose_name='Hujjatlar'),
        ),
    ]
