# Generated by Django 5.2 on 2025-05-28 12:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Mashina nomi (Make)')),
                ('model', models.CharField(max_length=100, verbose_name='Mashina nusxasi (Model)')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1886)], verbose_name='Yili (Year)')),
                ('horsepower', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ot kuchi (HP)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Narxi (Price)')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Kompaniya nomi')),
                ('location', models.CharField(max_length=100, verbose_name='Shtat (Location)')),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Dokumentlar')),
                ('sotilgan', models.BooleanField(default=False, verbose_name='Sotilgan')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('purchase_date', models.DateField(auto_now_add=True, verbose_name='Sotib olingan sana')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trucks/', verbose_name='Rasm')),
                ('seriya', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Seriya raqami')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Truck',
                'verbose_name_plural': 'Trucks',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['user', 'sotilgan', '-created_date'], name='trucks_truc_user_id_b89272_idx'), models.Index(fields=['make', 'model'], name='trucks_truc_make_4db56d_idx'), models.Index(fields=['seriya'], name='trucks_truc_seriya_947eaf_idx')],
            },
        ),
    ]
