# Generated by Django 5.2 on 2025-06-10 04:52

import django.core.validators
import django.db.models.deletion
import trucks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_id', models.CharField(help_text='PO-{raqam} formatida kiriting, masalan, PO-12345', max_length=50, unique=True, verbose_name='PO raqami')),
                ('make', models.CharField(max_length=100, verbose_name='Marka')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1886)], verbose_name='Yil')),
                ('horsepower', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ot kuchi (HP)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Narx')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Kompaniya nomi')),
                ('location', models.CharField(max_length=100, verbose_name='Joylashuv')),
                ('sotilgan', models.BooleanField(default=False, verbose_name='Sotilgan')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('purchase_date', models.DateField(auto_now_add=True, verbose_name='Sotib olingan sana')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trucks/', verbose_name='Rasm')),
                ('seriya', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Seriya raqami')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Yuk mashinasi',
                'verbose_name_plural': 'Yuk mashinalari',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='TruckHujjat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hujjat', models.FileField(upload_to=trucks.models.generate_unique_truck_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'])], verbose_name='Hujjat fayli')),
                ('original_file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Asl fayl nomi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hujjatlar', to='trucks.truck', verbose_name='Yuk mashinasi')),
            ],
            options={
                'verbose_name': 'Yuk mashinasi hujjati',
                'verbose_name_plural': 'Yuk mashinasi hujjatlari',
            },
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['po_id'], name='trucks_truc_po_id_b69c10_idx'),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['user', 'sotilgan'], name='trucks_truc_user_id_1468bd_idx'),
        ),
        migrations.AddIndex(
            model_name='truckhujjat',
            index=models.Index(fields=['truck'], name='trucks_truc_truck_i_87598a_idx'),
        ),
    ]
