# Generated by Django 5.2 on 2025-05-31 20:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='truck_documents/', verbose_name='Document')),
                ('document_name', models.CharField(blank=True, help_text='Name of the document as it will appear', max_length=200, verbose_name='Document Name')),
            ],
            options={
                'verbose_name': 'Truck Document',
                'verbose_name_plural': 'Truck Documents',
            },
        ),
        migrations.CreateModel(
            name='TruckImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='truck_images/', verbose_name='Image')),
                ('image_name', models.CharField(blank=True, help_text='Name of the image as it will appear', max_length=200, verbose_name='Image Name')),
            ],
            options={
                'verbose_name': 'Truck Image',
                'verbose_name_plural': 'Truck Images',
            },
        ),
        migrations.RemoveIndex(
            model_name='truck',
            name='trucks_truc_user_id_b89272_idx',
        ),
        migrations.RemoveIndex(
            model_name='truck',
            name='trucks_truc_seriya_947eaf_idx',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='image',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='seriya',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='sotilgan',
        ),
        migrations.AddField(
            model_name='truck',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AddField(
            model_name='truck',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Sold'),
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_id',
            field=models.CharField(default=1, help_text='Unique identifier for the truck', max_length=50, unique=True, verbose_name='Truck ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='horsepower',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Horsepower (HP)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1886)], verbose_name='Year'),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['user', 'sold', '-created_date'], name='trucks_truc_user_id_2580fa_idx'),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['truck_id'], name='trucks_truc_truck_i_8cc56c_idx'),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['serial_number'], name='trucks_truc_serial__d41963_idx'),
        ),
        migrations.AddField(
            model_name='truckdocument',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='trucks.truck', verbose_name='Truck'),
        ),
        migrations.AddField(
            model_name='truckimage',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trucks.truck', verbose_name='Truck'),
        ),
    ]
