# Generated by Django 5.2 on 2025-05-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_remove_truckdocument_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckdocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='truckdocument',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='truckdocument',
            name='is_image',
        ),
        migrations.AddField(
            model_name='truckdocument',
            name='document',
            field=models.FileField(default=1, upload_to='truck_documents/', verbose_name='Document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truckdocument',
            name='document_name',
            field=models.CharField(blank=True, help_text='Name of the document as it will appear', max_length=200, verbose_name='Document Name'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_id',
            field=models.CharField(help_text='Unique identifier for the truck', max_length=50, unique=True, verbose_name='Truck ID'),
        ),
    ]
