# Generated by Django 5.2 on 2025-05-31 21:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0004_remove_truckdocument_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckdocument',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='truckimage',
            name='truck',
        ),
        migrations.RemoveIndex(
            model_name='truck',
            name='trucks_truc_user_id_2580fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='truck',
            name='trucks_truc_truck_i_8cc56c_idx',
        ),
        migrations.RemoveIndex(
            model_name='truck',
            name='trucks_truc_serial__d41963_idx',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='truck_id',
        ),
        migrations.AddField(
            model_name='truck',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Dokumentlar'),
        ),
        migrations.AddField(
            model_name='truck',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trucks/', verbose_name='Rasm'),
        ),
        migrations.AddField(
            model_name='truck',
            name='seriya',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Seriya raqami'),
        ),
        migrations.AddField(
            model_name='truck',
            name='sotilgan',
            field=models.BooleanField(default=False, verbose_name='Sotilgan'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kompaniya nomi'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='description',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='horsepower',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ot kuchi (HP)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Shtat (Location)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Mashina nomi (Make)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Mashina nusxasi (Model)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Narxi (Price)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, verbose_name='Sotib olingan sana'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1886)], verbose_name='Yili (Year)'),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['user', 'sotilgan', '-created_date'], name='trucks_truc_user_id_b89272_idx'),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['seriya'], name='trucks_truc_seriya_947eaf_idx'),
        ),
        migrations.DeleteModel(
            name='TruckDocument',
        ),
        migrations.DeleteModel(
            name='TruckImage',
        ),
    ]
