# Generated by Django 5.2 on 2025-05-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0005_remove_truckdocument_truck_remove_truckimage_truck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='seriya',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Seriya raqami'),
        ),
    ]
