# Generated by Django 5.2 on 2025-05-31 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0006_alter_truck_seriya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='documents',
        ),
        migrations.CreateModel(
            name='TruckDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/', verbose_name='Dokument')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Fayl nomi')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='trucks.truck', verbose_name='Mashina')),
            ],
            options={
                'verbose_name': 'Truck Document',
                'verbose_name_plural': 'Truck Documents',
            },
        ),
    ]
