# Generated by Django 5.2 on 2025-06-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0007_remove_truck_documents_truckdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Hozirgi joylashuvi (Location)'),
        ),
    ]
