# Generated by Django 5.2 on 2025-06-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0008_alter_truck_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Dokumentlar'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Shtat (Location)'),
        ),
        migrations.DeleteModel(
            name='TruckDocument',
        ),
    ]
