# Generated by Django 5.2 on 2025-06-01 09:28

import django.core.validators
import django.db.models.deletion
import trucks.models
from django.conf import settings
from django.db import migrations, models
import uuid

def assign_unique_po_ids(apps, schema_editor):
    Truck = apps.get_model('trucks', 'Truck')
    for truck in Truck.objects.all():
        # Assign a unique po_id in the format PO-<random_string>
        truck.po_id = f"PO-{uuid.uuid4().hex[:8]}"
        truck.save()

class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0009_truck_documents_alter_truck_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create TruckHujjat model
        migrations.CreateModel(
            name='TruckHujjat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hujjat', models.FileField(upload_to=trucks.models.generate_unique_truck_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'])], verbose_name='Hujjat fayli')),
                ('original_file_name', models.CharField(max_length=255, verbose_name='Asl fayl nomi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
            ],
            options={
                'verbose_name': 'Truck hujjati',
                'verbose_name_plural': 'Truck hujjatlari',
            },
        ),
        # Remove documents field from Truck
        migrations.RemoveField(
            model_name='Truck',
            name='documents',
        ),
        # Add po_id field with null=True initially
        migrations.AddField(
            model_name='Truck',
            name='po_id',
            field=models.CharField(max_length=50, null=True, verbose_name='PO raqami'),
        ),
        # Run data migration to assign unique po_id values
        migrations.RunPython(assign_unique_po_ids),
        # Alter po_id to add unique=True and null=False
        migrations.AlterField(
            model_name='Truck',
            name='po_id',
            field=models.CharField(
                max_length=50,
                unique=True,
                verbose_name='PO raqami',
                help_text='PO-{raqam} formatida, masalan, PO-12345',
            ),
        ),
        # Add index for po_id
        migrations.AddIndex(
            model_name='Truck',
            index=models.Index(fields=['po_id'], name='trucks_truc_po_id_b69c10_idx'),
        ),
        # Add truck foreign key to TruckHujjat
        migrations.AddField(
            model_name='TruckHujjat',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hujjatlar', to='trucks.Truck', verbose_name='Truck'),
        ),
    ]