# Generated by Django 5.2 on 2025-06-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0010_truckhujjat_remove_truck_documents_truck_po_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='po_id',
            field=models.CharField(help_text="Faqat raqamlar kiriting, masalan, 12345 (PO- avtomatik qo'shiladi)", max_length=50, unique=True, verbose_name='PO raqami'),
        ),
    ]
