# Generated by Django 5.2 on 2025-06-02 11:41

import django.core.validators
import django.db.models.deletion
import trucks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0011_alter_truck_po_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truckhujjat',
            options={'verbose_name': 'Truck Document', 'verbose_name_plural': 'Truck Documents'},
        ),
        migrations.AlterField(
            model_name='truck',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='horsepower',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Horsepower (HP)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trucks/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='po_id',
            field=models.CharField(help_text='Enter a numeric PO number (e.g., 12345). It will be displayed as PO-12345.', max_length=50, unique=True, verbose_name='PO Number'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price ($)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='seriya',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='sotilgan',
            field=models.BooleanField(default=False, verbose_name='Sold'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1886)], verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='truckhujjat',
            name='hujjat',
            field=models.FileField(upload_to=trucks.models.generate_unique_truck_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'])], verbose_name='Document File'),
        ),
        migrations.AlterField(
            model_name='truckhujjat',
            name='original_file_name',
            field=models.CharField(max_length=255, verbose_name='Original File Name'),
        ),
        migrations.AlterField(
            model_name='truckhujjat',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At'),
        ),
    ]
