# Generated by Django 5.2 on 2025-06-02 12:17

import django.core.validators
import django.db.models.deletion
import trucks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0012_alter_truckhujjat_options_alter_truck_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truckhujjat',
            options={'verbose_name': 'Truck hujjati', 'verbose_name_plural': 'Truck hujjatlari'},
        ),
        migrations.AlterField(
            model_name='truck',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kompaniya nomi'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='description',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='horsepower',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ot kuchi (HP)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trucks/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Shtat (Location)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Mashina nomi (Make)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Mashina nusxasi (Model)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='po_id',
            field=models.CharField(help_text='PO-{raqam} formatida, masalan, PO-12345', max_length=50, unique=True, verbose_name='PO raqami'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Narxi (Price)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, verbose_name='Sotib olingan sana'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='seriya',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Seriya raqami'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='sotilgan',
            field=models.BooleanField(default=False, verbose_name='Sotilgan'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1886)], verbose_name='Yili (Year)'),
        ),
        migrations.AlterField(
            model_name='truckhujjat',
            name='hujjat',
            field=models.FileField(upload_to=trucks.models.generate_unique_truck_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'])], verbose_name='Hujjat fayli'),
        ),
        migrations.AlterField(
            model_name='truckhujjat',
            name='original_file_name',
            field=models.CharField(max_length=255, verbose_name='Asl fayl nomi'),
        ),
        migrations.AlterField(
            model_name='truckhujjat',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt'),
        ),
    ]
