# Generated by Django 5.2 on 2025-06-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0015_alter_truck_options_alter_truckhujjat_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='truck',
            name='trucks_truc_make_4db56d_idx',
        ),
        migrations.RemoveIndex(
            model_name='truck',
            name='trucks_truc_user_id_b89272_idx',
        ),
        migrations.RemoveIndex(
            model_name='truck',
            name='trucks_truc_seriya_947eaf_idx',
        ),
        migrations.RemoveField(
            model_name='truckhujjat',
            name='original_file_name',
        ),
    ]
