# Generated by Django 5.2 on 2025-06-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0016_remove_truck_trucks_truc_make_4db56d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckhujjat',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Asl fayl nomi'),
        ),
    ]
