# Generated by Django 5.2 on 2025-05-28 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Qarz miqdori')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Qoldiq miqdor')),
                ('given_date', models.DateField(auto_now_add=True, verbose_name='Qarz berilgan sana')),
                ('payment_due_date', models.DateField(blank=True, null=True, verbose_name='To‘lov muddati')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('is_paid', models.BooleanField(default=False, verbose_name='To‘langanmi?')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan sana')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_qarzlar', to=settings.AUTH_USER_MODEL, verbose_name='Qarz oluvchi')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_qarzlar', to=settings.AUTH_USER_MODEL, verbose_name='Qarz beruvchi')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qarzlar', to='trucks.truck', verbose_name='Mashina')),
            ],
            options={
                'verbose_name': 'Qarz',
                'verbose_name_plural': 'Qarzlar',
                'ordering': ['-given_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='To‘lov miqdori')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='To‘lov sanasi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('qarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='qarz.qarz', verbose_name='Qarz')),
            ],
            options={
                'verbose_name': 'To‘lov',
                'verbose_name_plural': 'To‘lovlar',
                'ordering': ['-payment_date'],
            },
        ),
    ]
