# Generated by Django 5.2 on 2025-06-10 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=100, verbose_name='Borrower Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Loan Amount')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Remaining Amount')),
                ('given_date', models.DateField(auto_now_add=True, verbose_name='Loan Issued Date')),
                ('payment_due_date', models.DateField(blank=True, null=True, verbose_name='Payment Due Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid?')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_loans', to=settings.AUTH_USER_MODEL, verbose_name='Lender')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='trucks.truck', verbose_name='Truck')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-given_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Payment Amount')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('qarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='qarz.qarz', verbose_name='Loan')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
