# Generated by Django 5.2 on 2025-06-01 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qarz', '0002_alter_payment_options_alter_qarz_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qarz',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='qarz',
            name='lender_name',
        ),
        migrations.AddField(
            model_name='qarz',
            name='borrower_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Borrower Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qarz',
            name='lender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='given_loans', to=settings.AUTH_USER_MODEL, verbose_name='Lender'),
            preserve_default=False,
        ),
    ]
