# Generated by Django 5.2 on 2025-06-10 04:52

import django.db.models.deletion
import django.utils.timezone
import xarajatlar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xarajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('repair', 'Repair'), ('fuel', 'Fuel'), ('insurance', 'Insurance'), ('parts', 'Spare Parts'), ('other', 'Other')], max_length=50, verbose_name='Expense Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('document', models.FileField(blank=True, null=True, upload_to=xarajatlar.models.xarajat_document_upload_path, verbose_name='Document')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trucks.truck', verbose_name='Truck')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date'],
            },
        ),
    ]
