# Generated by Django 5.2 on 2025-05-28 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xarajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xarajat_turi', models.CharField(choices=[('ta’mir', 'Ta’mir'), ('yoqilgi', 'Yoqilg‘i'), ('sug‘urta', 'Sug‘urta'), ('qismlar', 'Ehtiyot qismlar'), ('boshqa', 'Boshqa')], max_length=50, verbose_name='Xarajat turi')),
                ('miqdor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor (Summa)')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('sana', models.DateField(verbose_name='Sana')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xarajatlar', to='trucks.truck', verbose_name='Mashina')),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ['-sana'],
            },
        ),
    ]
