# Generated by Django 5.2 on 2025-06-01 20:52

import django.db.models.deletion
import xarajatlar.models
from django.db import migrations, models
import datetime
import decimal

class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0010_truckhujjat_remove_truck_documents_truck_po_id_and_more'),
        ('xarajatlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xarajat',
            options={'ordering': ['-date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.RemoveField(
            model_name='xarajat',
            name='izoh',
        ),
        migrations.RemoveField(
            model_name='xarajat',
            name='miqdor',
        ),
        migrations.RemoveField(
            model_name='xarajat',
            name='sana',
        ),
        migrations.RemoveField(
            model_name='xarajat',
            name='xarajat_turi',
        ),
        migrations.AddField(
            model_name='xarajat',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal("1.00"), max_digits=10, verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xarajat',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 2), verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xarajat',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='xarajat',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=xarajatlar.models.xarajat_document_upload_path, verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='xarajat',
            name='expense_type',
            field=models.CharField(choices=[('repair', 'Repair'), ('fuel', 'Fuel'), ('insurance', 'Insurance'), ('parts', 'Spare Parts'), ('other', 'Other')], default="repair", max_length=50, verbose_name='Expense Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trucks.truck', verbose_name='Truck'),
        ),
    ]