# Generated by Django 5.2 on 2025-06-01 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarajatlar', '0002_alter_xarajat_options_remove_xarajat_izoh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xarajat',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
