# Generated by Django 5.2 on 2025-06-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarajatlar', '0003_alter_xarajat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xarajat',
            name='date',
            field=models.DateField(default='2025-06-02', verbose_name='Date'),
        ),
    ]
