# Generated by Django 5.2 on 2025-06-01 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarajatlar', '0004_alter_xarajat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xarajat',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 2), verbose_name='Date'),
        ),
    ]
