# Generated by Django 5.2 on 2025-06-02 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarajatlar', '0005_alter_xarajat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xarajat',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
